# Generated by Django 4.1.2 on 2023-03-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel('Profile'),
    ]
