# Generated by Django 4.1.2 on 2023-03-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0005_remove_todo_user_todo_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="owner",
            new_name="user",
        ),
    ]
