# Generated by Django 4.1.2 on 2023-03-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0006_rename_owner_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
